version: '3'

services:
  apache:
    image: apache
    build: ./apache
    ports:
      - 80:80
    volumes:
      - ${WEBDEV_FOLDER}:/www

  php70:
    image: php70
    build: ./php70
    volumes:
      - ${WEBDEV_FOLDER}:/www
    depends_on:
      - apache
      - mariadb

  php74:
    image: php74
    build: ./php74
    volumes:
      - ${WEBDEV_FOLDER}:/www
    depends_on:
      - apache
      - mariadb

  # php74-openssl-downgraded:
  #   image: php74-openssl-downgraded
  #   build: ./php74-openssl-downgraded
  #   volumes:
  #     - ${WEBDEV_FOLDER}:/www
  #   depends_on:
  #     - apache
  #     - mariadb

  mariadb:
    image: mariadb:10.3
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8080:80
    depends_on:
      - mariadb